<?php 
////find out if the form has been submitted...
if ($_SERVER['REQUEST_METHOD'] == 'POST'){
//connect to the database...
require('../connect_db.php');
//clean up the message and assign it to a variable...
$message = mysqli_real_escape_string($dbc,trim($_POST['message']));
//insert message into quotes table of database...
$query = mysqli_query($dbc,"INSERT INTO messages (message, poster_id, project_id, role) VALUES ('$message','$_POST[message_id]','$_POST[project_id]','$_POST[role]')");
}
header('location:messages.php?id=' . $_POST['project_id'] . '&&poster=' . $_POST['message_id']);
?>